services:
  db:
    container_name: pg_db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
     - db-data:/var/lib/postgresql/data


  pgadmin:
    container_name: pgadmin_db
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: gabroliveiraalvesdasilva@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
        - pgadmin-data:/var/lib/pgadmin
volumes:
 db-data:
 pgadmin-data:
